vaadin/vaadin-grid-pro-flow

vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/10)
=> Bump wc dependency to 1.0.0-alpha5

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/19)
=> Bump dependencies versions

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/21)
=> Bump dependencies

vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
Fixes #22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/23)
=> Add overload with sorting props

pom.xml, vaadin-grid-pro-flow-demo/src/main/java/com/vaadin/flow/component/gridpro/vaadincom/GridProView.java, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/pom.xml, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
Connected to #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/32)
=> Add custom representation of the value in edit column

vaadin-grid-pro-flow-demo/src/main/java/com/vaadin/flow/component/gridpro/vaadincom/GridProView.java, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow-testbench/src/main/java/com/vaadin/flow/component/gridpro/testbench/GridProColumnElement.java, vaadin-grid-pro-flow-testbench/src/main/java/com/vaadin/flow/component/gridpro/testbench/GridProElement.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
Fixes #28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/34)
=> Improve sorting functionality

vaadin-grid-pro-flow-demo/src/main/java/com/vaadin/flow/component/gridpro/vaadincom/GridProView.java, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/37)
=> Rename the method, convert it to overload of addEditColumn

vaadin-grid-pro-flow-demo/src/main/java/com/vaadin/flow/component/gridpro/vaadincom/GridProView.java, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/pom.xml, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditorType.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/osgi/GridProConnectorResource.java, vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/editColumnConnector.js, vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js, vaadin-grid-pro-flow/src/test/java/com/vaadin/flow/component/gridpro/GridProTest.java
Fixes #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/38)
=> Add custom editor

vaadin-grid-pro-flow-demo/src/main/java/com/vaadin/flow/component/gridpro/vaadincom/GridProView.java, vaadin-grid-pro-flow/pom.xml, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/EditColumnConfigurator.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java, vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js, vaadin-grid-pro-flow/src/test/java/com/vaadin/flow/component/gridpro/GridProTest.java
Fixes #36
Fixes #40 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/41)
=> Single cell edit

pom.xml
License is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/45)
=> Add CVAL3 entry in parent pom

.travis.yml, pom.xml, vaadin-grid-pro-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-pro-flow-integration-tests/src/main/webapp/frontend/bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/46)
=> Run tests in both NPM and BOWER modes

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/49)
=> Update versions for rc1

vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/50)
=> Bump vaadin-grid-flow to rc2

vaadin-grid-pro-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/51)
=> Remove vaadin-components-testbench dependency

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/53)
=> Prepare for rc2

vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/55)
=> Bump vaadin-grid-pro wc dependency to 2.0.2

vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/City.java, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/Person.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
Fixes https://github.com/vaadin/vaadin-grid-pro-flow/issues/56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/58)
=> Fix json serialization

pom.xml, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/59)
=> Bump grid-pro npm annotation to 2.0.2

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/60)
=> Bump dependencies versions to stable

vaadin-grid-pro-flow/pom.xml, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/61)
=> Bump versions of dependant components

pom.xml, vaadin-grid-pro-flow/pom.xml
- Use property for grid version
- Set other properties common in other components
- Removed duplicated dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/72)
=> Align configuration with other components

pom.xml, vaadin-grid-pro-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/73)
=> Fix configuration for release

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-pro-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/74)
=> Use snapshots

vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
Connected to https://github.com/vaadin/components-team-tasks/issues/479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-pro-flow/62)
=> Improve error handling in connector: wrap with try catch

vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
=> Fix setEnabled for GridPro

pom.xml, vaadin-grid-pro-flow-demo/pom.xml, vaadin-grid-pro-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-pro-flow-integration-tests/pom.xml, vaadin-grid-pro-flow-testbench/pom.xml, vaadin-grid-pro-flow/pom.xml, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
=> Bump version for V14.3

vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
fix #94
Add a test for the case reported by the issue. The fix comes from the WC, so this test is expected to fail until the WC version with the fix is released.
Blocked by https://github.com/vaadin/vaadin-grid-pro/pull/128
=> test: add test for custom editor

vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
=> test: add test for custom editor (#103)

vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java, vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
This is a PR for V17 (master branch).
=> Bump web component version to 2.2.2
